openapi: 3.0.0
info:
  title: FarmStall API
  version: v1
servers:
  - url: https://farmstall.ponelat.com/v1
paths:
  /reviews:
    get:
      description: Get a bunch of reviews.
      parameters:
        - name: maxRating
          description: Filter the reviews by the maximum rating
          in: query
          schema:
            type: number
      responses:
        '200':
          description: A bunch of reviews
